Update clone_repository.mdx
Cloud-Code-AI/kaizen pull request #499
Opened 2024-08-30 14:15 UTC by SwapnilChand

Replaced https://github.com/cloudcode/cloudcode.git
with the correct url https://github.com/cloud-code-ai/kaizen

2024-08-30 16:54 UTC, sauravpanda requested changes

2024-08-30 16:54 UTC, sauravpanda commented on docs/pages/self_hosting_guide/clone_repository.mdx
> +This command will clone the CloudCode repository from GitHub to your local machine.
Make it “kaizen repository”

2024-08-30 20:45 UTC, SwapnilChand commented
Done

2024-08-31 02:29 UTC, sauravpanda approved these changes

2024-08-31 02:29 UTC, merged